# Generated by Django 5.2.7 on 2025-10-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('universe', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('power', models.TextField()),
                ('image1', models.ImageField(upload_to='spider_folder1/')),
                ('image2', models.ImageField(upload_to='spider_folder2/')),
            ],
        ),
    ]
