# Generated by Django 5.2.7 on 2025-10-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='image1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='spider',
            name='image2',
            field=models.URLField(),
        ),
    ]
