# Generated by Django 5.2.7 on 2025-10-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_spider_image1_alter_spider_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('universe', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('power', models.TextField()),
                ('image1', models.URLField()),
                ('image2', models.URLField()),
            ],
        ),
    ]
