# Generated by Django 5.2.7 on 2025-10-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_villain'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='image3',
            field=models.URLField(null=True),
        ),
    ]
